#!/bin/bash

# This script is a hook called via the dt-install-sandbox-software command.
# Do not run it directly.

[ -z "$1" ] && echo "Run dt-install-sandbox-software to call this script" && exit 1

if [ "$1" != "--env-loaded" ]; then
	# THIS IS DEPRACATED. To eliminate:  echo 2 >CS_BROWSER_TOP/sandbox/sandbox-version
	[ -z "$2" ] && echo "Run dt-install-sandbox-software (version 1) to call this script" && exit 1
	export CS_BROWSER_SANDBOX=$1  # root of the sandbox
	export CS_BROWSER_TOP=$2      # root of the primary git project
	SB_ENV_FILE=$3            # name of the environment file to use
	export CS_BROWSER_NAME=`dirname $CS_BROWSER_SANDBOX`
	[ -z "$SB_ENV_FILE" ] && SB_ENV_FILE=defaults.sh
	. $CS_BROWSER_TOP/sandbox/$SB_ENV_FILE
fi

# Install node if specified with CS_BROWSER_NODE_VER
[ -n "$CS_BROWSER_NODE_VER" -a ! -L $CS_BROWSER_SANDBOX/node ] && dt-get-software -V $CS_BROWSER_NODE_VER node $CS_BROWSER_SANDBOX

# Install yarn if specified with CS_BROWSER_YARN_VER
[ -n "$CS_BROWSER_YARN_VER" -a ! -L $CS_BROWSER_SANDBOX/yarn ] && dt-get-software -V $CS_BROWSER_YARN_VER yarn $CS_BROWSER_SANDBOX



# Put custom one-time only software installations here (such as git clones of additional repos,
# other software packages that will live in the sandbox, etc...).
#
# Note that there is no sandbox process, other than a first time install, that exeutes this hook.


exit 0
